name: ebook
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

##############################################################################
dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.0

##############################################################################
dev_dependencies:

  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

##############################################################################
flutter:
  uses-material-design: true

  ##############################################################################
  assets:
    - assets/images/

  ##############################################################################
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700
