name: ebook
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

##############################################################################
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.2.0

##############################################################################
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

##############################################################################
flutter:
  uses-material-design: true

##############################################################################
  assets:
    - assets/images/

##############################################################################
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

